// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: mc/comm/pbactlogic.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBActLogic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogicClass string `protobuf:"bytes,1,opt,name=logic_class,json=logicClass,proto3" json:"logic_class,omitempty"`
	Properties string `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"` // 用于初始化上述 class 的数据, 由于 class 不一致，此信息交由 class 本身处理
}

func (x *PBActLogic) Reset() {
	*x = PBActLogic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mc_comm_pbactlogic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBActLogic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBActLogic) ProtoMessage() {}

func (x *PBActLogic) ProtoReflect() protoreflect.Message {
	mi := &file_mc_comm_pbactlogic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBActLogic.ProtoReflect.Descriptor instead.
func (*PBActLogic) Descriptor() ([]byte, []int) {
	return file_mc_comm_pbactlogic_proto_rawDescGZIP(), []int{0}
}

func (x *PBActLogic) GetLogicClass() string {
	if x != nil {
		return x.LogicClass
	}
	return ""
}

func (x *PBActLogic) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

var File_mc_comm_pbactlogic_proto protoreflect.FileDescriptor

var file_mc_comm_pbactlogic_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x70, 0x62, 0x61, 0x63, 0x74, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x63, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x22, 0x4d, 0x0a, 0x0a, 0x50, 0x42, 0x41, 0x63, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x6d, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mc_comm_pbactlogic_proto_rawDescOnce sync.Once
	file_mc_comm_pbactlogic_proto_rawDescData = file_mc_comm_pbactlogic_proto_rawDesc
)

func file_mc_comm_pbactlogic_proto_rawDescGZIP() []byte {
	file_mc_comm_pbactlogic_proto_rawDescOnce.Do(func() {
		file_mc_comm_pbactlogic_proto_rawDescData = protoimpl.X.CompressGZIP(file_mc_comm_pbactlogic_proto_rawDescData)
	})
	return file_mc_comm_pbactlogic_proto_rawDescData
}

var file_mc_comm_pbactlogic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mc_comm_pbactlogic_proto_goTypes = []interface{}{
	(*PBActLogic)(nil), // 0: mc.comm.PBActLogic
}
var file_mc_comm_pbactlogic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mc_comm_pbactlogic_proto_init() }
func file_mc_comm_pbactlogic_proto_init() {
	if File_mc_comm_pbactlogic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mc_comm_pbactlogic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBActLogic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mc_comm_pbactlogic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mc_comm_pbactlogic_proto_goTypes,
		DependencyIndexes: file_mc_comm_pbactlogic_proto_depIdxs,
		MessageInfos:      file_mc_comm_pbactlogic_proto_msgTypes,
	}.Build()
	File_mc_comm_pbactlogic_proto = out.File
	file_mc_comm_pbactlogic_proto_rawDesc = nil
	file_mc_comm_pbactlogic_proto_goTypes = nil
	file_mc_comm_pbactlogic_proto_depIdxs = nil
}
