// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: mc/comm/pbmodel.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BinBuffer string  `protobuf:"bytes,1,opt,name=bin_buffer,json=binBuffer,proto3" json:"bin_buffer,omitempty"`
	Begin     int32   `protobuf:"varint,2,opt,name=begin,proto3" json:"begin,omitempty"`
	Length    int32   `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	EboLength int32   `protobuf:"varint,4,opt,name=ebo_length,json=eboLength,proto3" json:"ebo_length,omitempty"`
	EboType   int32   `protobuf:"varint,5,opt,name=ebo_type,json=eboType,proto3" json:"ebo_type,omitempty"`
	Attrib    []int32 `protobuf:"varint,6,rep,packed,name=attrib,proto3" json:"attrib,omitempty"`
}

func (x *PBModel) Reset() {
	*x = PBModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mc_comm_pbmodel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBModel) ProtoMessage() {}

func (x *PBModel) ProtoReflect() protoreflect.Message {
	mi := &file_mc_comm_pbmodel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBModel.ProtoReflect.Descriptor instead.
func (*PBModel) Descriptor() ([]byte, []int) {
	return file_mc_comm_pbmodel_proto_rawDescGZIP(), []int{0}
}

func (x *PBModel) GetBinBuffer() string {
	if x != nil {
		return x.BinBuffer
	}
	return ""
}

func (x *PBModel) GetBegin() int32 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *PBModel) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *PBModel) GetEboLength() int32 {
	if x != nil {
		return x.EboLength
	}
	return 0
}

func (x *PBModel) GetEboType() int32 {
	if x != nil {
		return x.EboType
	}
	return 0
}

func (x *PBModel) GetAttrib() []int32 {
	if x != nil {
		return x.Attrib
	}
	return nil
}

var File_mc_comm_pbmodel_proto protoreflect.FileDescriptor

var file_mc_comm_pbmodel_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x70, 0x62, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x63, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x22, 0xa8, 0x01, 0x0a, 0x07, 0x50, 0x42, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x69, 0x6e, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x65, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x62, 0x6f,
	0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x62, 0x6f, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x62, 0x6f, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x62, 0x6f, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x06, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x42, 0x09, 0x5a, 0x07, 0x6d,
	0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mc_comm_pbmodel_proto_rawDescOnce sync.Once
	file_mc_comm_pbmodel_proto_rawDescData = file_mc_comm_pbmodel_proto_rawDesc
)

func file_mc_comm_pbmodel_proto_rawDescGZIP() []byte {
	file_mc_comm_pbmodel_proto_rawDescOnce.Do(func() {
		file_mc_comm_pbmodel_proto_rawDescData = protoimpl.X.CompressGZIP(file_mc_comm_pbmodel_proto_rawDescData)
	})
	return file_mc_comm_pbmodel_proto_rawDescData
}

var file_mc_comm_pbmodel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mc_comm_pbmodel_proto_goTypes = []interface{}{
	(*PBModel)(nil), // 0: mc.comm.PBModel
}
var file_mc_comm_pbmodel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mc_comm_pbmodel_proto_init() }
func file_mc_comm_pbmodel_proto_init() {
	if File_mc_comm_pbmodel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mc_comm_pbmodel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mc_comm_pbmodel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mc_comm_pbmodel_proto_goTypes,
		DependencyIndexes: file_mc_comm_pbmodel_proto_depIdxs,
		MessageInfos:      file_mc_comm_pbmodel_proto_msgTypes,
	}.Build()
	File_mc_comm_pbmodel_proto = out.File
	file_mc_comm_pbmodel_proto_rawDesc = nil
	file_mc_comm_pbmodel_proto_goTypes = nil
	file_mc_comm_pbmodel_proto_depIdxs = nil
}
