// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: mc/comm/pbmaterial.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBMaterial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtLogic      string   `protobuf:"bytes,1,opt,name=art_logic,json=artLogic,proto3" json:"art_logic,omitempty"`
	TextureList   []string `protobuf:"bytes,2,rep,name=texture_list,json=textureList,proto3" json:"texture_list,omitempty"`
	ShaderProgram string   `protobuf:"bytes,3,opt,name=shader_program,json=shaderProgram,proto3" json:"shader_program,omitempty"`
}

func (x *PBMaterial) Reset() {
	*x = PBMaterial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mc_comm_pbmaterial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBMaterial) ProtoMessage() {}

func (x *PBMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_mc_comm_pbmaterial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBMaterial.ProtoReflect.Descriptor instead.
func (*PBMaterial) Descriptor() ([]byte, []int) {
	return file_mc_comm_pbmaterial_proto_rawDescGZIP(), []int{0}
}

func (x *PBMaterial) GetArtLogic() string {
	if x != nil {
		return x.ArtLogic
	}
	return ""
}

func (x *PBMaterial) GetTextureList() []string {
	if x != nil {
		return x.TextureList
	}
	return nil
}

func (x *PBMaterial) GetShaderProgram() string {
	if x != nil {
		return x.ShaderProgram
	}
	return ""
}

var File_mc_comm_pbmaterial_proto protoreflect.FileDescriptor

var file_mc_comm_pbmaterial_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x70, 0x62, 0x6d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x63, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x22, 0x73, 0x0a, 0x0a, 0x50, 0x42, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x68, 0x61, 0x64, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x09, 0x5a, 0x07, 0x6d, 0x63, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mc_comm_pbmaterial_proto_rawDescOnce sync.Once
	file_mc_comm_pbmaterial_proto_rawDescData = file_mc_comm_pbmaterial_proto_rawDesc
)

func file_mc_comm_pbmaterial_proto_rawDescGZIP() []byte {
	file_mc_comm_pbmaterial_proto_rawDescOnce.Do(func() {
		file_mc_comm_pbmaterial_proto_rawDescData = protoimpl.X.CompressGZIP(file_mc_comm_pbmaterial_proto_rawDescData)
	})
	return file_mc_comm_pbmaterial_proto_rawDescData
}

var file_mc_comm_pbmaterial_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mc_comm_pbmaterial_proto_goTypes = []interface{}{
	(*PBMaterial)(nil), // 0: mc.comm.PBMaterial
}
var file_mc_comm_pbmaterial_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mc_comm_pbmaterial_proto_init() }
func file_mc_comm_pbmaterial_proto_init() {
	if File_mc_comm_pbmaterial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mc_comm_pbmaterial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBMaterial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mc_comm_pbmaterial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mc_comm_pbmaterial_proto_goTypes,
		DependencyIndexes: file_mc_comm_pbmaterial_proto_depIdxs,
		MessageInfos:      file_mc_comm_pbmaterial_proto_msgTypes,
	}.Build()
	File_mc_comm_pbmaterial_proto = out.File
	file_mc_comm_pbmaterial_proto_rawDesc = nil
	file_mc_comm_pbmaterial_proto_goTypes = nil
	file_mc_comm_pbmaterial_proto_depIdxs = nil
}
