// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: mc/comm/pbtexture.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBTexture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MagFilter   int32    `protobuf:"varint,1,opt,name=magFilter,proto3" json:"magFilter,omitempty"`
	MinFilter   int32    `protobuf:"varint,2,opt,name=minFilter,proto3" json:"minFilter,omitempty"` // GL_LINEAR 0x2601 9729
	WrapS       int32    `protobuf:"varint,3,opt,name=wrapS,proto3" json:"wrapS,omitempty"`
	WrapT       int32    `protobuf:"varint,4,opt,name=wrapT,proto3" json:"wrapT,omitempty"`
	Image       string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	WrapR       int32    `protobuf:"varint,6,opt,name=wrapR,proto3" json:"wrapR,omitempty"` // GL_CLAMP_TO_EDGE 0x812F 33071
	ImageList   []string `protobuf:"bytes,7,rep,name=image_list,json=imageList,proto3" json:"image_list,omitempty"`
	TextureType int32    `protobuf:"varint,8,opt,name=texture_type,json=textureType,proto3" json:"texture_type,omitempty"` // 3553(GL_TEXTURE_2D) 34067(GL_TEXTURE_CUBE_MAP)
}

func (x *PBTexture) Reset() {
	*x = PBTexture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mc_comm_pbtexture_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBTexture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBTexture) ProtoMessage() {}

func (x *PBTexture) ProtoReflect() protoreflect.Message {
	mi := &file_mc_comm_pbtexture_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBTexture.ProtoReflect.Descriptor instead.
func (*PBTexture) Descriptor() ([]byte, []int) {
	return file_mc_comm_pbtexture_proto_rawDescGZIP(), []int{0}
}

func (x *PBTexture) GetMagFilter() int32 {
	if x != nil {
		return x.MagFilter
	}
	return 0
}

func (x *PBTexture) GetMinFilter() int32 {
	if x != nil {
		return x.MinFilter
	}
	return 0
}

func (x *PBTexture) GetWrapS() int32 {
	if x != nil {
		return x.WrapS
	}
	return 0
}

func (x *PBTexture) GetWrapT() int32 {
	if x != nil {
		return x.WrapT
	}
	return 0
}

func (x *PBTexture) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PBTexture) GetWrapR() int32 {
	if x != nil {
		return x.WrapR
	}
	return 0
}

func (x *PBTexture) GetImageList() []string {
	if x != nil {
		return x.ImageList
	}
	return nil
}

func (x *PBTexture) GetTextureType() int32 {
	if x != nil {
		return x.TextureType
	}
	return 0
}

var File_mc_comm_pbtexture_proto protoreflect.FileDescriptor

var file_mc_comm_pbtexture_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x70, 0x62, 0x74, 0x65, 0x78, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x63, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x22, 0xe1, 0x01, 0x0a, 0x09, 0x50, 0x42, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x72, 0x61, 0x70, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x72, 0x61,
	0x70, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x72, 0x61, 0x70, 0x54, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x77, 0x72, 0x61, 0x70, 0x54, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x72, 0x61, 0x70, 0x52, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77,
	0x72, 0x61, 0x70, 0x52, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x65, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x6d, 0x63, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mc_comm_pbtexture_proto_rawDescOnce sync.Once
	file_mc_comm_pbtexture_proto_rawDescData = file_mc_comm_pbtexture_proto_rawDesc
)

func file_mc_comm_pbtexture_proto_rawDescGZIP() []byte {
	file_mc_comm_pbtexture_proto_rawDescOnce.Do(func() {
		file_mc_comm_pbtexture_proto_rawDescData = protoimpl.X.CompressGZIP(file_mc_comm_pbtexture_proto_rawDescData)
	})
	return file_mc_comm_pbtexture_proto_rawDescData
}

var file_mc_comm_pbtexture_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mc_comm_pbtexture_proto_goTypes = []interface{}{
	(*PBTexture)(nil), // 0: mc.comm.PBTexture
}
var file_mc_comm_pbtexture_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mc_comm_pbtexture_proto_init() }
func file_mc_comm_pbtexture_proto_init() {
	if File_mc_comm_pbtexture_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mc_comm_pbtexture_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBTexture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mc_comm_pbtexture_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mc_comm_pbtexture_proto_goTypes,
		DependencyIndexes: file_mc_comm_pbtexture_proto_depIdxs,
		MessageInfos:      file_mc_comm_pbtexture_proto_msgTypes,
	}.Build()
	File_mc_comm_pbtexture_proto = out.File
	file_mc_comm_pbtexture_proto_rawDesc = nil
	file_mc_comm_pbtexture_proto_goTypes = nil
	file_mc_comm_pbtexture_proto_depIdxs = nil
}
